#!/bin/sh
# autopkgtest check: very few things to test without other subcommands
# (C) 2021 Jose Luis Rivero
# Author: Jose Luis Rivero <jrivero@osrfoundation.org>

set -e

WORKDIR=$(mktemp -d)
#trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.5.1 FATAL_ERROR)

project(example)

# Find the gz-plugin library
find_package(gz-plugin REQUIRED COMPONENTS all)
add_executable(plugin_test plugin_test.cc)
target_link_libraries(plugin_test
  PRIVATE
    gz-plugin::register
    gz-plugin::loader
)

EOF

cat <<EOF2 > plugin_test.cc
#include <gz/plugin/Loader.hh>
#include <gz/plugin/Register.hh>

class Drive
{
  public: virtual ~Drive() = default;
};


class CautiousBot : public virtual Drive
{
};

GZ_ADD_PLUGIN(CautiousBot,
    CautiousBot::Drive)

int main(int argc, char** argv) {
  gz::plugin::Loader pl;

  return 0;
}
EOF2

cmake .
echo "configure: OK"
make
echo "build: OK"

./plugin_test
echo "plugin_test run: OK"
